### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Lorenzooone** [ChrisMalnick/xx3dsfml#10]
Something which I just noticed is missing is a License specifying how the code can be shared/used by other users.
I understand that you're new to Github, however you should take your time to understand the licensing system (I sometimes forgot about doing it myself).
It will help other users contribute and protect you from possible liability!

Github's GUI should have an easy way to add that, as well as descriptions about what each license entails.

**Comment by ChrisMalnick** [comment]
I'm really sorry for the delay on this. I had thought that there was some implied license that's assumed when code is uploaded to GitHub without an explicit license attached. This may have actually been the case years ago and has possibly changed since then, but I can't remember. Regardless, I was still planning to put something together when I saw this, but I didn't realize it was as pressing as it is! In any case, a license has been added with the latest release. Thanks for bringing this to my attention.
