### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by GremlinGremlin** [ChrisMalnick/xx3dsfml#12]
I'm completely and entirely new to anything like this. I just want to record my new3DS on my mac, and wasn't expecting having to do what looks like programming. I think I have successfully installed the prerequisites, I think the makefile has successfully built. The problem is that the xx3dsfml command doesnt do anything. If i try to open the file itself, nothing happens.

<img width="1162" alt="Screenshot 2024-04-05 at 2 19 20 PM" src="https://github.com/ChrisMalnick/xx3dsfml/assets/166177127/52d7a587-1610-4ac8-98b9-196a54d44fca">

**Comment by Lorenzooone** [comment]
Hi, if you use the #6 fork, does it work?
Direct download: https://github.com/Lorenzooone/xx3dsfml/archive/refs/heads/new_main_changes.zip
If you still have issues and you have Discord, I can try to help you a bit. My username on there is: lorenzooone .

**Comment by ChrisMalnick** [comment]
Hey there, first off, sorry for any grief this may have been causing you. I know how hard it can be to have to work with computers in ways that are completely unfamiliar. It really reminds me of my younger days! :P

What you seem to have experienced here appears to do entirely with where brew installed SFML and its dependencies on your system and how it made them visible (or failed to in this case) to your system. I'm not actually all that familiar with brew, and I only linked to it in my README just to make people aware that things like it even exist in the first place.

Looking at the Makefile from @Lorenzooone, I see that there's some additional content dealing with brew itself. While this can be helpful for cases like this, I'm not sure how I feel about it in the long run. Adding support for system specific dependencies can get out of hand really quickly, and it's hard to say where to draw the line.

The most ideal solution to this would be to provide precompiled binaries. Once the code has slowed down in development, it may be worth seeing if anyone from the forums would be willing to share the binaries that they've compiled so that they can be added here for others to use. Though in the meantime, it may be worth opening something on the forums to allow for open discussion so that solutions to topics like this can be visibly shared and documented.

If you are still having issues with this though, please let me know.
