### ISSUE TITLE
Fedora does not check /usr/local/lib

### ISSUE THREAD

**Issue by soko7awen** [ChrisMalnick/xx3dsfml#13]
Hey there, I am using Fedora 39 and had some trouble getting things to work.
First, when I ran `sudo make install` it installed successfully.
Then, I tried running the application and got this error:
`xx3dsfml: error while loading shared libraries: libftd3xx.so: cannot open shared object file: No such file or directory`
So, after some searching I learned I had to include /usr/local/lib using ldconfig.
After doing that, it did run but with only a black screen and this error:
```
[xx3dsfml] File "xx3dsfml.conf" load failed.
[xx3dsfml] Create failed.
Failed to compile fragment shader:
0:1(81): error: no matching function for call to 'texture2D(sampler2D, vec4)'; candidates are:
0:1(81): error:    vec4 texture2D(sampler2D, vec2)
0:1(81): error:    vec4 texture2D(sampler2D, vec2, float)
0:1(81): error: operands to arithmetic operators must be numeric
```

**Comment by ChrisMalnick** [comment]
Hi there, thanks for bringing these issues to my attention. I just put out release v1.5.1 that hopefully addresses them. The reason why you're getting a black screen is actually due to the Create failed error. Everything else following in your output log wouldn't have prevented the software from working, though you wouldn't have had access to the brightness controls, so I addressed it anyway. I'm assuming that the Create failed might be due to insufficient permission for accessing the device over USB. There are many ways for applying these types of permissions on Linux, so until now, I'd just left it up to the users to decide. Since FTDI provides a file for Linux users that grants the needed permissions though, I've updated the Makefile to take advantage of it, so hopefully this will solve your issue. If not, I'd be happy to help diagnose this further, so please let me know!

**Comment by hhamelin** [comment]
It's working perfect for me now! Thanks.
