### ISSUE TITLE
Im stupid and cant compile.

### ISSUE THREAD

**Issue by ThingyMajiger** [ChrisMalnick/xx3dsfml#2]
(unfortunate) Mac user here.
When I run `xcrun make`
I get 
```
g++ -c xx3dsfml.cpp -o xx3dsfml.o
xx3dsfml.cpp:6:10: fatal error: 'libftd3xx/ftd3xx.h' file not found
#include <libftd3xx/ftd3xx.h>
         ^~~~~~~~
1 error generated.
make: *** [xx3dsfml.o] Error 1
```
I may be stupid. Any help is appreciated.

**Comment by ChrisMalnick** [comment]
Hey there, I'm assuming you've installed the ftd3xx driver by copying the linked library to the /usr/lib or /usr/local/lib directory and by creating a version independent symbolic link to it within that same directory. One additional step that needs to be done after that as mentioned in my README is to create the libftd3xx directory in the /usr/include directory and copy the ftd3xx.h and Types.h header files to it. These files came with the Linux version of the driver, so I'm guessing they come with the Mac version as well. If you've done this already though, then there may be a permissions issue going on. Let me know what you've done so far with the ftd3xx driver, and I can try to help you from there.

**Comment by kobacat** [comment]
Hi there, I'm not the same person who made the issue originally but I did have a similar problem and I believe I know why it happened- macOS Ventura (at least in my experience) made the /usr/include directory a little bit more hard to find, so I had to trace back the path to /Library/Developer/CommandLineTools/usr/include to be able to make the libftd3xx folder, and that did seem to fix the issue Maji had.

However, I did want to bring up that I did come across another issue that, I'm unsure if it's related to the root problem that the issue brings up. Specifically, I get a library related issue.

`xx3dsfml-main % make
g++ -c xx3dsfml.cpp -o xx3dsfml.o
xx3dsfml.cpp:74:47: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
        bool onGetData(sf::SoundStream::Chunk &data) override {
                                                     ^
xx3dsfml.cpp:88:35: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
        void onSeek(sf::Time timeOffset) override {}
                                         ^
2 warnings generated.
g++ xx3dsfml.o -o xx3dsfml -lftd3xx -lsfml-audio -lsfml-graphics -lsfml-system -lsfml-window
ld: library not found for -lftd3xx
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [xx3dsfml] Error 1`

I'm not sure if this is due to user error or otherwise, but some clarification on why this might be happening would be helpful if possible, thanks!

**Comment by ChrisMalnick** [comment]
Hey Koba, you have in fact succeeded in creating the object file, meaning that you did solve the OP's issue with the header files. (Just to note, you can actually put the header files in the project's directory itself, but you would need to update the include statement in the xx3dsfml.cpp file from `#include <libftd3xx/ftd3xx.h>` to `#include "ftd3xx.h"`. I don't know how this skipped my mind the first time this was brought up, but I'm really sorry for not having mentioned it sooner.)

The issue you're facing now is indeed having to do with the linked library. As I mentioned in my previous post here, you have to copy the library file to one of your system's library paths and create a symbolic link to it. On Linux, we have .so files and on Windows, there's .dll files. On Mac, you might be working with something like a .dylib file. I haven't looked at the installation instructions FTDI provides for Mac, and if you haven't already, I would suggest looking there (it might be for the older D2XX driver, but it should still be applicable). 

If you still can't manage to figure it out, I can try to take a closer look as to how you do this sort of thing on Mac and might be able to advise you on what to do.

**Comment by kobacat** [comment]
Hi Chris, thanks for the quick response! I appreciate it.

I looked into it more and I managed to get it working! After checking your comments to check the FTDI instructions, I found this section and this allowed me to get through past the FTD3XX error.
<img width="596" alt="image" src="https://github.com/ChrisMalnick/xx3dsfml/assets/22461806/c7bf650a-d02a-48e6-8497-b3b36bed8efa">
I ran into a similar issue with SFML even after installing it via the Homebrew package manager, however after downloading t[he latest ARM files for macOS from here](https://www.sfml-dev.org/download/sfml/2.6.1/), I was able to move all of the files to /usr/local/lib and it appeared to compile perfectly from there.
<img width="1440" alt="Screenshot 2024-01-20 at 1 29 54 AM" src="https://github.com/ChrisMalnick/xx3dsfml/assets/22461806/c633126b-0273-4787-8644-b8c2d6303723">
I have run into a few random crashes but besides that, it seems to have been running pretty well. Hopefully this helps show the process for it to be compiled on macOS, albeit with a different process than I figured it would be haha

**Comment by kobacat** [comment]
Hi, just figured I'd drop an update- the software has been working pretty well but still crashing consistently every hour or so, it seems to be some sort of SIGBUS error from something in the source code- not really sure if it's something that would persist on other OSes besides Mac, but I figure dropping the error details here might be useful if you're willing to take a look at it.

https://pastebin.com/eJjvPUpT

I've still been loving the software even with the crashes though! If I were to suggest anything, I think a volume slider + having the volume settings save even when relaunching would definitely be nice to have.

**Comment by ChrisMalnick** [comment]
Hi Koba, glad to see you managed to get it working! Sorry to hear about the crashes though. I haven't experienced anything like that myself and haven't heard anyone else mention something like it yet either. That said, I just put out an update to the code that changes how the audio is handled which I'm hoping might solve your issue. It reduces the amount of asynchronous memory management related to queuing the audio and frankly should have been written this way in the first place. (It also reduces the default volume from 50 to 10 as I found it to be pretty loud even at 50.) You should be able to replace your local copy of the xx3dsfml.cpp file with the new one here and just recompile it. Let me know if it helps, and if not, I'll have to look more specifically into what could be causing the issue.

Also, I appreciate the feedback. Unfortunately, there's no standard set of UI elements that I can use to implement menus with controls like how you're suggesting. I would either have to switch to a different framework, find something that could be universally imported cross platform, or create the UI elements myself. It is a good suggestion though, and I'm open to looking into it.

If I do get something like that in place, I would then put all of the controls in menus with the ability to configure custom keybindings for them and have all of these settings stored in a local file to save them like you mentioned. I would probably also add things like breaking out the screens into separate windows and having non-integer scaling tied to a slider that snaps at every integer.

I'd also like to have an overlay that displays what the scaling, blur, rotation, volume, mute, etc. is currently set to and could be toggled on and off so that you can see at a glance without it being intrusive, possibly even having it display in the blanked out areas around the bottom screen. The most important thing to me though is performance, so I'd like to try to get everything ironed out before I start expanding the feature set.

**Comment by ChrisMalnick** [comment]
Hey again, I just wanted to add here that I recently put out a major update which overhauled the program pretty significantly, and I just put out the first v1.0.0 release for it in fact. Beyond improving the performance and adding features, I think some of these changes will have addressed your issues as well. Being that the current issue being discussed here isn't related to the initial issue (and the fact that it may have been addressed here already in the first place), I'll be closing this issue for the time being. You can always open a new issue or continue to comment on here, and I can reopen this issue if necessary.
