### ISSUE TITLE
[xx3dsfml] Create failed.

### ISSUE THREAD

**Issue by NO-ob** [ChrisMalnick/xx3dsfml#3]
Hi I built the application it seemed to build properly

```
(づ◡﹏◡)づ [xx3dsfml]$ make
g++ xx3dsfml.o -o xx3dsfml -lftd3xx -lsfml-audio -lsfml-graphics -lsfml-system -lsfml-window
```

but when running it just says 

```
./xx3dsfml 
[xx3dsfml] Create failed.
```

i can see a window but it's black 

![image](https://github.com/ChrisMalnick/xx3dsfml/assets/15161159/82d4ee0b-d15e-4110-b7c2-9047d5d27717)

I modified the outdated arch pkgbuild for libftd3xx this is the file layout, I think this is correct 
![image](https://github.com/ChrisMalnick/xx3dsfml/assets/15161159/cb52f5b5-77d5-4dab-bfd1-c8345f13a5d4)

With lsusb i can see what i think is the 3ds capture card
```
Bus 003 Device 014: ID 0403:601e Future Technology Devices International, Ltd FT600 16-bit FIFO IC
```

**Comment by NO-ob** [comment]
Oh dw it was because my 3ds is the .2 model

**Comment by ChrisMalnick** [comment]
Hey, thanks for using my software! I assume that since this was closed as completed, you managed to get it working by changing the `PRODUCT` macro in the code to `N3DSXL.2` and recompiling. Even if that's the case, I figured I'd mention that I just put out an update to how the audio is handled. It may not make any impact for you (as it didn't for me as far as I can tell), but I'm hoping it will help with another issue that's currently open. In any case, it shouldn't hurt to update, and if it somehow does, you can always roll back.

**Comment by NO-ob** [comment]
> Hey, thanks for using my software! I assume that since this was closed as completed, you managed to get it working by changing the `PRODUCT` macro in the code to `N3DSXL.2` and recompiling. Even if that's the case, I figured I'd mention that I just put out an update to how the audio is handled. It may not make any impact for you (as it didn't for me as far as I can tell), but I'm hoping it will help with another issue that's currently open. In any case, it shouldn't hurt to update, and if it somehow does, you can always roll back.
 Thankyou for making it, it's great. yeah changing the product macro got it working. i have updated now
