### ISSUE TITLE
[xx3dsfml] Create failed.

### ISSUE THREAD

**Issue by TheBluekr** [ChrisMalnick/xx3dsfml#5]
Hi, I've managed to compile after issues in setting up but ran into "Create failed" when running. Contrary to #3 I don't get a window to show up at all.
I've verified the device is showing up using lsusb and ran the latest version of the main branch.

For added context I'm running Arch with the latest updates and used libftd3xx version 1.0.14

**Comment by ChrisMalnick** [comment]
Hi, first off, thanks for trying out my code! :) Glad to hear that you were able to get it to compile. I would imagine that if anything were set up improperly, then it wouldn't compile at all, so we could probably rule out anything having to do with your initial setup issues here.

As for the window not showing up, I recently changed the way in which the program handles the device by requiring the device to be connected for the program to even continue running, so it's really just a red herring in this case.

Now as to why the create for the device is failing is a bit of a head-scratcher. I also happened to recently changed the program so that it first tries to create a handle for the original board (N3DSXL) before it tries creating one for the revision (N3DSXL.2). I have the original model only, but I did test the logic by switching the order that's processed (N3DSXL.2 before N3DSXL). In both cases, my device is recognized, and the handle is created.

I know that people with the board revision have been using my software, so if you have the revised board, I would expect it to work too. Either way, could you try running this command and checking for either N3DSXL or N3DSXL.2 in the output?

`lsusb -v | grep 'N3DSXL'`

I would also be curious what the ID is for the device that's reported by lsusb. Mine is 0403:601f, and I believe the revision uses 0403:601e. Funnily enough, I actually unintentionally changed my board's PID to 601e when I was first getting started developing software for it, so I know it's possible for it to become incorrectly set.

Also, I'm assuming you're on Linux since you're using lsusb, but it really shouldn't matter in this case anyway. :P

**Comment by TheBluekr** [comment]
I've received `iProduct                2 N3DSXL.2` and the device ID is `0403:601e` so those match.
Weirdly enough I've tried running today and this time it properly grabs it and it works out of the box. I haven't tried yet with the 1.0.0 release and will try in a bit, will edit this if necessary.

Only difference in the setup compared to when I posted this issue was running the connection through a AC7047 instead of a direct connection to the laptop I use. Weirdly enough it did show up under lsusb so might need to test further on that. Earliest I can do is tomorrow. So for now I would consider this issue resolved but I'll keep it open until I can test tomorrow again.

**Comment by ChrisMalnick** [comment]
Ah, computers acting unpredictably. No surprise there. Glad you got it working though and didn't even have to compromise your setup either. I went and added a note to the README about using an indirect connection, so I definitely appreciate that you raised the issue in the first place. I also added a note to the release stating that it's more of a snapshot and that the latest code can always be found in the main branch, so thanks for bringing that up as well.

Anyway, I hope the software is performing well at least and is meeting your expectations. Thanks again for even trying it out. I really do appreciate it! :D
