### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by Starport75** [ChrisMalnick/xx3dsfml#7]
Hello!

My current setup has two monitors, one for each screen. Would it be possible to add in the ability to go full screen, where the current screen is centered with black borders?

This software is fantastic, thank you so much for all the hard work you put into it!! It's perfect for setting up a dedicated Raspberry Pi for 3DS streaming

**Comment by ChrisMalnick** [comment]
Hi there, I'm glad to hear that the software's been serving you well so far. It's always neat to see how people have been using it, especially when dedicated hardware like a Pi is involved!

Based on your suggestion here, I actually just quickly demoed the idea on my system by using the first video mode available to it, and in comical fashion, it stretched the entire contents of the screen across both of my monitors! Implementing full screen rendering is a bit more complex than it probably seems and only more so when multiple monitors are involved since you can't always predict what a user might be intending to do.

In any case, I took a quick look at the SFML documentation regarding windowing and found the following:
> Multiple monitors are not correctly supported yet
> 
> SFML doesn't explicitly manage multiple monitors. As a consequence, you won't be able to choose which monitor a window appears on, and you won't be able to create more than one fullscreen window. This should be improved in a future version. 

I could stand to mess around with it some more just to see what I can do, but I think until this is addressed within SFML itself, I wouldn't even be able to implement it to its **fullest** (pun **fully** intended :P) potential anyway. For this reason, I'm going to close the issue as not planned, but if there's any developments regarding SFML in the future as they've stated, it can always be opened again.
