### ISSUE TITLE
X error when xx3dsfml.conf is missing

### ISSUE THREAD

**Issue by Gudf** [ChrisMalnick/xx3dsfml#9]
When xx3dsfml.conf is missing, the scale (m_scale) ends up being 0, which causes an X error when attempting to create the window:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  58
  Current serial number in output stream:  59
```

Because the program uses relative paths, this means you can only run it in a directory where xx3dsfml.conf is present (and populated correctly). It would be more practical to have sensible default values for each configuration option in case the configuration file is missing or incomplete, and use a standard path for the configuration and preset files, such as $XDG_CONFIG_HOME/xx3dsfml/ (or $HOME/.config/xx3dsfml/ if XDG_CONFIG_HOME is missing/empty) on Linux.

**Comment by Lorenzooone** [comment]
This PR will fix the issue you're having.
It sets sane defaults.
https://github.com/ChrisMalnick/xx3dsfml/pull/6

**Comment by ChrisMalnick** [comment]
This was something that I was already aware of and had even mentioned in the Notes section of the README. I'd been on the fence as to where the config/layout files should be kept but decided to just keep them in the same directory as everything else for the time being. The mislocated config file would lead to a clean abort and prevent new config files from being written in unintended places. It was a bit of a bandaid, and arguably, so is the change I introduced to address it.

The code now initializes the member variables of the Screen object where declared, and the files are now checked prior to IO with a flag being set when the config file is not available to prevent additional config files from being created. This unfortunately prevents a new config file from being created in instances where you would want one to be though (i.e. the program is running from the intended directory, but the config file is actually just missing).

Config and preset files are often kept in a user specific location, this being the user's .config directory on Linux for example (with environment variables being available like you mentioned). I'd like to keep the actual code as system independent and dependency free as possible though, so I'd have to come up with a solution that also works cleanly on Mac at the very least. At that point, I would even modify the Makefile to install the actual executable to a standard system location (i.e. the \bin directory on Linux) which would prevent the need for aliasing.

I'm going to leave this issue open for now even though the actual error has been addressed. I would consider the universal config/layout file location to be more of a feature request than an issue being that many applications are locally contained and utilize relative files for portability (something I personally like, even if it is restrictive). Since feature requests aren't a thing on GitHub though, an issue is really the only way to keep something like this tracked.

I'll be taking this into consideration, but for the time being, I would suggest using an alias like the following if it suits you (or anyone else): `alias xx3dsfml='cd /absolute/path/to/code && /absolute/path/to/code/xx3dsfml'`

**Comment by ChrisMalnick** [comment]
As discussed previously, the executable has been moved to a systemwide directory, and the config/layout files are now automatically (re)created per user in their local config directory in [release v1.3.0](https://github.com/ChrisMalnick/xx3dsfml/releases/tag/v1.3.0).
